import { cpSync, existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, sep } from "node:path";
import { afterEach, describe, expect, it, vi } from "vitest";
import { cachePathFor } from "../src/cache/db.js";
import { main } from "../src/cli.js";
import {
  emptyConfig,
  fixtureConfig,
  fixtureRoot,
  generatedConfig,
  solutionConfig,
} from "./helpers.js";

/**
 * The CLI's contract with a harness is its exit code, so every case here
 * asserts the code first and the message second. Streams are captured rather
 * than silenced so a regression that stops explaining itself is caught too.
 */
function capture() {
  const out: string[] = [];
  const err: string[] = [];
  vi.spyOn(process.stdout, "write").mockImplementation((chunk) => {
    out.push(String(chunk));
    return true;
  });
  vi.spyOn(process.stderr, "write").mockImplementation((chunk) => {
    err.push(String(chunk));
    return true;
  });
  return { stdout: () => out.join(""), stderr: () => err.join("") };
}

const temps: string[] = [];

/** A throwaway copy of the sample fixture, so a test may write a cache into it. */
function scratchProject(): { root: string; config: string } {
  const root = mkdtempSync(join(tmpdir(), "thicket-cli-"));
  temps.push(root);
  cpSync(fixtureRoot(), root, {
    recursive: true,
    filter: (src) => !src.split(sep).includes(".thicket"),
  });
  return { root, config: join(root, "tsconfig.json") };
}

afterEach(() => {
  vi.restoreAllMocks();
  while (temps.length > 0) rmSync(temps.pop()!, { recursive: true, force: true });
});

describe("main", () => {
  it("exits 0 and prints a report for a config with source files", async () => {
    const io = capture();
    expect(await main(["--config", fixtureConfig()])).toBe(0);
    expect(io.stdout()).toContain("# thicket report");
  });

  it("exits non-zero when the project has no source files", async () => {
    const io = capture();
    expect(await main(["--config", emptyConfig()])).not.toBe(0);
    expect(io.stdout()).not.toContain("# thicket report");
    expect(io.stderr()).toMatch(/no source files/i);
  });

  it("names the config and the likely cause when the project is empty", async () => {
    const io = capture();
    await main(["--config", emptyConfig()]);
    expect(io.stderr()).toContain("fixtures/empty/tsconfig.json");
    expect(io.stderr()).toMatch(/references|include/i);
  });

  it("rejects an empty --config instead of silently analyzing the cwd", async () => {
    const io = capture();
    expect(await main(["--config", ""])).not.toBe(0);
    expect(io.stderr()).toMatch(/--config/);
    expect(io.stdout()).toBe("");
  });

  it("exits non-zero for a nonexistent config path", async () => {
    const io = capture();
    expect(await main(["--config", "/definitely/not/here/tsconfig.json"])).not.toBe(0);
    expect(io.stderr()).toContain("/definitely/not/here/tsconfig.json");
    expect(io.stdout()).toBe("");
  });

  it("--include-generated puts the excluded files back", async () => {
    const off = capture();
    await main(["--config", generatedConfig()]);
    const offFiles = off.stdout();
    vi.restoreAllMocks();
    const on = capture();
    await main(["--config", generatedConfig(), "--include-generated"]);
    // 4 hand-written, plus 2 generated directories and 2 banner-marked files.
    expect(offFiles).toMatch(/4 files/);
    expect(on.stdout()).toMatch(/8 files/);
  });

  it("states what it did not analyze, so a thinned corpus is visible", async () => {
    // The counts above are drawn from what survives the filters. A run that
    // silently analyzed half the tree is the failure this line exists to stop.
    const io = capture();
    await main(["--config", generatedConfig()]);
    expect(io.stdout()).toMatch(
      /\*\*Not analyzed:\*\* 4 generated files — 2 in generated directories, 2 marked generated by a banner comment\./,
    );
  });

  it("--exclude drops matching files and says so", async () => {
    const io = capture();
    await main(["--config", generatedConfig(), "--exclude", "**/distance/**"]);
    expect(io.stdout()).toMatch(/3 files/);
    expect(io.stdout()).toMatch(/1 matching --exclude/);
  });

  it("--no-banner-scan turns off just that opinion, leaving the others", async () => {
    // The banner sniff is an opinion -- "this text means a machine wrote it"
    // -- and every opinion here has to be switchable on its own. Turning it
    // off must NOT drag the directory rule back on with it.
    const io = capture();
    await main(["--config", generatedConfig(), "--no-banner-scan"]);
    // The 4 hand-written files plus the 2 the banner rule was dropping.
    expect(io.stdout()).toMatch(/6 files/);
    expect(io.stdout()).toMatch(/2 in generated directories/);
    expect(io.stdout()).not.toMatch(/banner comment/);
  });

  it("--exclude survives --include-generated, because it is an instruction", async () => {
    const io = capture();
    await main([
      "--config",
      generatedConfig(),
      "--include-generated",
      "--exclude",
      "**/distance/**",
    ]);
    expect(io.stdout()).toMatch(/7 files/);
  });

  it("rejects an unknown --types mode instead of quietly analyzing everything", async () => {
    // A typo'd mode that fell back to the default would be indistinguishable
    // from asking for the default, and every number in the report would be
    // drawn from a half the reader did not choose.
    const io = capture();
    expect(await main(["--config", fixtureConfig(), "--types", "typs"])).not.toBe(0);
    expect(io.stdout()).toBe("");
    expect(io.stderr()).toMatch(/--types must be include, exclude, or only/);
  });

  it("analyzes a solution-style config rather than reporting it empty", async () => {
    const io = capture();
    expect(await main(["--config", solutionConfig()])).toBe(0);
    expect(io.stdout()).toMatch(/3 files/);
  });

  it("--no-cache leaves no cache behind and reports the same thing", async () => {
    const { root, config } = scratchProject();
    const io = capture();
    expect(await main(["--config", config, "--no-cache"])).toBe(0);
    const plain = io.stdout();
    expect(existsSync(cachePathFor(root))).toBe(false);

    vi.restoreAllMocks();
    const cached = capture();
    expect(await main(["--config", config])).toBe(0);
    expect(existsSync(cachePathFor(root))).toBe(true);
    expect(cached.stdout()).toBe(plain);
  });

  it("cache clear removes the project's cache, and says so either way", async () => {
    const { root, config } = scratchProject();
    capture();
    await main(["--config", config]);
    expect(existsSync(cachePathFor(root))).toBe(true);

    vi.restoreAllMocks();
    const io = capture();
    expect(await main(["cache", "clear", "--config", config])).toBe(0);
    expect(existsSync(cachePathFor(root))).toBe(false);
    expect(existsSync(join(root, ".thicket"))).toBe(false);
    expect(io.stdout()).toBe("");
    expect(io.stderr()).toMatch(/cleared/);

    vi.restoreAllMocks();
    const again = capture();
    expect(await main(["cache", "clear", "--config", config])).toBe(0);
    expect(again.stderr()).toMatch(/no cache/);
  });

  it("rejects an unknown command instead of analyzing anyway", async () => {
    const io = capture();
    expect(await main(["cache", "burn", "--config", fixtureConfig()])).not.toBe(0);
    expect(io.stdout()).toBe("");
    expect(io.stderr()).toMatch(/unknown command/);
  });
});

describe("main diff", () => {
  /** Writes a sidecar by actually running a report, so the shape is the real one. */
  async function sidecar(config: string, name: string, into: string): Promise<string> {
    const path = join(into, name);
    const io = capture();
    expect(await main(["--config", config, "--json", path, "--no-cache"])).toBe(0);
    io.stdout();
    vi.restoreAllMocks();
    return path;
  }

  it("compares two sidecars and names what was resolved", async () => {
    const { root, config } = scratchProject();
    const before = await sidecar(config, "before.json", root);
    // Delete one copy of the duplicated function.
    const beta = join(root, "src/beta.ts");
    const bodies = readFileSync(beta, "utf8").split(/\n\n(?=export function )/);
    writeFileSync(beta, bodies.slice(0, -1).join("\n\n").trimEnd() + "\n");
    const after = await sidecar(config, "after.json", root);

    const io = capture();
    expect(await main(["diff", before, after])).toBe(0);
    expect(io.stdout()).toMatch(/[1-9]\d* findings? resolved/);
    expect(io.stdout()).toMatch(/THK-DUP-[0-9a-f]{8}/);
    expect(io.stdout()).toContain("propagation cost");
  });

  it("needs no tsconfig in the working directory", async () => {
    // `--config` defaults to ./tsconfig.json. A diff analyzes nothing, so
    // requiring one would break the command everywhere but a project root.
    const { root, config } = scratchProject();
    const before = await sidecar(config, "before.json", root);
    const io = capture();
    const cwd = process.cwd();
    process.chdir(tmpdir());
    try {
      expect(await main(["diff", before, before])).toBe(0);
    } finally {
      process.chdir(cwd);
    }
    expect(io.stdout()).toContain("0 findings resolved");
    expect(io.stderr()).toBe("");
  });

  it("rejects a wrong number of arguments", async () => {
    const io = capture();
    expect(await main(["diff", "only-one.json"])).not.toBe(0);
    expect(io.stdout()).toBe("");
    expect(io.stderr()).toMatch(/two report paths/);
  });

  it("names the file it could not read", async () => {
    const io = capture();
    expect(await main(["diff", "/no/such/before.json", "/no/such/after.json"])).not.toBe(0);
    expect(io.stderr()).toContain("/no/such/before.json");
  });

  it("names the file that is not a report", async () => {
    const { root, config } = scratchProject();
    const good = await sidecar(config, "good.json", root);
    const junk = join(root, "junk.json");
    writeFileSync(junk, `{"hello":"world"}\n`);
    const io = capture();
    expect(await main(["diff", good, junk])).not.toBe(0);
    expect(io.stderr()).toContain("junk.json");
    expect(io.stderr()).toMatch(/not a thicket report/);
  });
});
