import { describe, expect, it } from "vitest";
import {
  GENERATED_DIR_SEGMENTS,
  hasGeneratedBanner,
  isExcludedByPattern,
  isGeneratedPath,
} from "../src/extract/exclude.js";
import { openProject } from "../src/extract/ts-adapter.js";
import { generatedConfig } from "./helpers.js";

describe("isGeneratedPath", () => {
  it("excludes a top-level generated directory", () => {
    expect(isGeneratedPath("dist/foo.ts")).toBe(true);
  });

  it("excludes a generated directory nested anywhere in the path", () => {
    expect(isGeneratedPath("packages/a/.next/x.ts")).toBe(true);
    expect(isGeneratedPath("apps/web/.next/types/validator.ts")).toBe(true);
  });

  it("matches whole segments, never substrings", () => {
    // Each of these contains a listed name as a substring and is real source.
    expect(isGeneratedPath("src/distance/foo.ts")).toBe(false);
    expect(isGeneratedPath("src/outbound.ts")).toBe(false);
    expect(isGeneratedPath("src/builders/index.ts")).toBe(false);
    expect(isGeneratedPath("src/outcomes/reducer.ts")).toBe(false);
    expect(isGeneratedPath("src/dist-tags.ts")).toBe(false);
  });

  it("does not treat a file named after a generated directory as generated", () => {
    expect(isGeneratedPath("src/build.ts")).toBe(false);
    expect(isGeneratedPath("out.ts")).toBe(false);
  });

  it("covers every segment the constant lists", () => {
    for (const seg of GENERATED_DIR_SEGMENTS) {
      expect(isGeneratedPath(`${seg}/x.ts`)).toBe(true);
    }
  });
});

describe("hasGeneratedBanner", () => {
  // The load-bearing case. On a sample monorepo 3407 of 6626 analyzed files
  // were machine-emitted re-export shims named `Icon3d.ts` -- no directory and
  // no filename pattern reaches them. What reaches them is what the generator
  // itself wrote at the top of the file.
  it("recognizes a generator's own banner regardless of the file's name", () => {
    expect(hasGeneratedBanner("// Auto-generated - do not edit manually\nexport const a = 1;\n")).toBe(
      true,
    );
    expect(hasGeneratedBanner("// @generated\nexport const a = 1;\n")).toBe(true);
    expect(
      hasGeneratedBanner("/* eslint-disable */\n\n// @ts-nocheck\n\n// This file was automatically generated by X.\n"),
    ).toBe(true);
    expect(hasGeneratedBanner("// Code generated by protoc. DO NOT EDIT.\n")).toBe(true);
  });

  it("requires a claim of generation, not merely a warning against editing", () => {
    // A hand-written file may well say "do not edit". That is not a claim that
    // a machine wrote it, and excluding it would silently drop real source.
    expect(
      hasGeneratedBanner("// Do not edit this without updating the schema.\nexport const a = 1;\n"),
    ).toBe(false);
    expect(hasGeneratedBanner("// DO NOT MODIFY without a review.\n")).toBe(false);
  });

  it("reads only the leading comment block", () => {
    // Otherwise any file that discusses code generation excludes itself.
    expect(
      hasGeneratedBanner('export function f() {\n  return "automatically generated by a machine";\n}\n'),
    ).toBe(false);
    expect(hasGeneratedBanner("const a = 1;\n// This file was automatically generated.\n")).toBe(false);
  });

  it("does not scan an unbounded prefix", () => {
    // A file that opens with a very long licence comment must not cost a scan
    // proportional to its size on every run.
    const licence = `${"// ".repeat(1)}${"lorem ipsum ".repeat(2000)}\n`;
    expect(hasGeneratedBanner(`${licence}// automatically generated\n`)).toBe(false);
  });
});

describe("isExcludedByPattern", () => {
  it("matches a repo-relative path against a glob", () => {
    expect(isExcludedByPattern("packages/ui/src/icons/Icon3d.ts", ["**/icons/**"])).toBe(true);
    expect(isExcludedByPattern("src/app.ts", ["**/icons/**"])).toBe(false);
  });

  it("is false when no patterns are given", () => {
    expect(isExcludedByPattern("anything.ts", [])).toBe(false);
  });

  it("accepts any of several patterns", () => {
    expect(isExcludedByPattern("src/table.gen.ts", ["**/*.pb.ts", "**/*.gen.ts"])).toBe(true);
  });
});

describe("openProject generated filtering", () => {
  it("drops generated directories by default and keeps look-alike source", async () => {
    const project = await openProject(generatedConfig());
    expect(project.files().map((f) => f.path)).toEqual([
      "src/distance/measure.ts",
      "src/handwritten.ts",
      "src/mentions.ts",
      "src/outbound.ts",
    ]);
  });

  it("keeps everything when asked to", async () => {
    const project = await openProject(generatedConfig(), { includeGenerated: true });
    expect(project.files().map((f) => f.path)).toEqual([
      "dist/emitted.ts",
      "packages/a/.next/validator.ts",
      "src/distance/measure.ts",
      "src/handwritten.ts",
      "src/mentions.ts",
      "src/outbound.ts",
      "src/table.gen.ts",
      "src/widgets/badge.ts",
    ]);
  });

  it("drops a banner-marked file that no directory or name rule would catch", async () => {
    const paths = (await openProject(generatedConfig())).files().map((f) => f.path);
    expect(paths).not.toContain("src/widgets/badge.ts");
    expect(paths).not.toContain("src/table.gen.ts");
  });

  it("applies --exclude patterns on top", async () => {
    const project = await openProject(generatedConfig(), { exclude: ["**/distance/**"] });
    expect(project.files().map((f) => f.path)).toEqual([
      "src/handwritten.ts",
      "src/mentions.ts",
      "src/outbound.ts",
    ]);
  });

  it("reports what it dropped, and why", async () => {
    const project = await openProject(generatedConfig(), { exclude: ["**/distance/**"] });
    expect(project.excluded).toEqual({ directory: 2, banner: 2, pattern: 1 });
  });
});
