import { matchesGlob } from "node:path";

/**
 * Directory names whose contents are generated, vendored, or built rather
 * than written — excluded from analysis by default.
 *
 * Machine-emitted code is duplication by construction: on one test repository
 * the two highest-scoring findings in the entire report were 32 and 14 copies
 * of a framework's emitted type validators. They are not refactorable, and
 * under a report budget they displace real findings one for one.
 *
 * TRADEOFF: `dist`, `build`, `out` and `generated` are plausible names for
 * hand-written source directories. Excluding them is a recall loss for those
 * layouts, accepted because the far commoner case is that they hold build
 * output, and a report dominated by build output is useless in a way that a
 * report missing one directory is not. Two things bound the damage:
 *
 *  1. Matching is on whole path SEGMENTS, never substrings. `src/distance/`,
 *     `src/outbound.ts` and `dist-tags.ts` are all kept — a substring match
 *     would silently drop them.
 *  2. `--include-generated` turns the whole list off, and the report states
 *     its file count, so a run that analyzed too little is visible.
 */
export const GENERATED_DIR_SEGMENTS: readonly string[] = [
  ".cache",
  ".gen",
  ".next",
  ".output",
  ".svelte-kit",
  ".turbo",
  "__generated__",
  "build",
  "coverage",
  "dist",
  "generated",
  "out",
];

const GENERATED = new Set(GENERATED_DIR_SEGMENTS);

/**
 * True when any whole segment of `relPath` names a generated directory.
 *
 * Takes a repo-relative path on purpose. Run against an absolute path this
 * would exclude every file in a checkout that happens to live under a
 * directory called `build`, which is a real way to analyze nothing at all.
 */
export function isGeneratedPath(relPath: string): boolean {
  const segments = relPath.split("/");
  // The last segment is the file name; a file named `dist.ts` is source.
  for (let i = 0; i < segments.length - 1; i++) {
    if (GENERATED.has(segments[i]!)) return true;
  }
  return false;
}

/**
 * How far into a file the banner may appear. A generator's banner is the first
 * thing in the file; a bound stops a long licence header from making this scan
 * proportional to file size on every run.
 */
const BANNER_SCAN_BYTES = 4096;

/**
 * A claim that a machine wrote this file.
 *
 * Deliberately narrower than "warns you not to edit it". A hand-written file
 * may perfectly well open with "do not edit without updating X" — treating
 * that as generated silently drops real source, which is the one failure this
 * whole mechanism must not have. The marker has to assert generation.
 */
const GENERATION_CLAIM =
  /@generated\b|\bauto[- ]?generated\b|\bautomatically[- ]generated\b|\bgenerated (?:by|from|with)\b/i;

/**
 * True when the file's leading comment block says a machine wrote it.
 *
 * This is the general mechanism, and on the evidence the load-bearing one.
 * Directory names and filename patterns are both conventions a project may or
 * may not follow: on one sample monorepo, 3407 of 6626 analyzed files were
 * machine-emitted re-export shims sitting in an ordinary directory under
 * ordinary names (`Icon3d.ts`), reachable by no path rule at all — while the
 * one file a `*.gen.ts` pattern would have caught was a single 5016-line route
 * table. What both had in common was a banner the generator wrote itself.
 * `@generated`, "auto-generated" and "Code generated by …" are cross-ecosystem
 * conventions, so this needs no per-project configuration; `--exclude` covers
 * generated code that declares nothing.
 *
 * Only the leading comment block is read. A file that merely *discusses* code
 * generation further down is source, and scanning the whole text would exclude
 * it.
 */
export function hasGeneratedBanner(text: string): boolean {
  let inBlockComment = false;
  for (const raw of text.slice(0, BANNER_SCAN_BYTES).split("\n")) {
    const line = raw.trim();
    if (line === "") continue;
    if (inBlockComment) {
      if (GENERATION_CLAIM.test(line)) return true;
      if (line.includes("*/")) inBlockComment = false;
      continue;
    }
    if (line.startsWith("//") || line.startsWith("/*")) {
      if (GENERATION_CLAIM.test(line)) return true;
      if (line.startsWith("/*") && !line.includes("*/")) inBlockComment = true;
      continue;
    }
    if (line.startsWith("#!")) continue;
    // The first line of real code ends the banner.
    return false;
  }
  return false;
}

/**
 * True when `relPath` matches any caller-supplied glob.
 *
 * The escape hatch for generated code that carries no banner. Kept separate
 * from the heuristics above because it is an instruction rather than a guess:
 * `--include-generated` turns the guesses off and leaves these in force.
 */
export function isExcludedByPattern(relPath: string, patterns: readonly string[]): boolean {
  return patterns.some((p) => matchesGlob(relPath, p));
}
