/**
 * Emits the Homebrew formula for the current dist-bin/ artifacts.
 *
 * Generated rather than checked in as a template with holes: the formula has
 * to name four URLs and four sha256s that must match bytes this build just
 * produced, and a template is exactly the kind of restated shape AGENTS.md
 * warns about -- it agrees with whatever it was last edited to say, while the
 * artifacts move underneath it.
 *
 * The formula installs the whole directory into libexec and symlinks only the
 * binary, because tsgo must stay a sibling of the executable: `tsgo-path.ts`
 * finds it at `dirname(process.execPath)/tsgo/tsc`, and `process.execPath`
 * resolves THROUGH the bin/ symlink to the real libexec location.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const pkg = JSON.parse(readFileSync(join(repoRoot, "package.json"), "utf8")) as {
  version: string;
  description: string;
};
const VERSION = pkg.version;
const REPO = process.env.THICKET_REPO ?? "alecf/thicket";
const base = `https://github.com/${REPO}/releases/download/v${VERSION}`;

const checksums = new Map<string, string>();
for (const line of readFileSync(join(repoRoot, "dist-bin", "checksums.txt"), "utf8").split("\n")) {
  const m = line.match(/^([0-9a-f]{64})\s+(\S+)$/);
  if (m) checksums.set(m[2]!, m[1]!);
}

function block(platform: string, arch: string, indent: string): string {
  const file = `thicket-${VERSION}-${platform}-${arch}.tar.gz`;
  const sha = checksums.get(file);
  if (!sha) throw new Error(`no checksum for ${file}; run \`bun run build:all\` first`);
  return `${indent}url "${base}/${file}"\n${indent}sha256 "${sha}"`;
}

const formula = `# Generated by scripts/homebrew-formula.ts -- do not edit by hand.
class Thicket < Formula
  desc "${pkg.description}"
  homepage "https://alecf.github.io/thicket/"
  version "${VERSION}"
  license "MIT"

  on_macos do
    on_arm do
${block("darwin", "arm64", "      ")}
    end
    on_intel do
${block("darwin", "x64", "      ")}
    end
  end

  on_linux do
    on_arm do
${block("linux", "arm64", "      ")}
    end
    on_intel do
${block("linux", "x64", "      ")}
    end
  end

  def install
    # The whole directory, not just the binary: analysis runs through a native
    # tsgo child process that lives in tsgo/ and refuses to start without the
    # lib.*.d.ts files beside it.
    libexec.install Dir["*"]
    # A symlink rather than a wrapper script. thicket locates tsgo from
    # process.execPath, which resolves through this symlink to libexec.
    bin.install_symlink libexec/"thicket"
  end

  test do
    (testpath/"src").mkpath
    (testpath/"src/a.ts").write <<~TS
      export function first(n: number): number {
        return n + 1;
      }
    TS
    (testpath/"tsconfig.json").write <<~JSON
      {
        "compilerOptions": { "target": "es2022", "module": "nodenext", "strict": true },
        "include": ["src/**/*.ts"]
      }
    JSON

    output = shell_output("#{bin}/thicket --config #{testpath}/tsconfig.json --no-cache")
    assert_match "# thicket report", output
    # Proves tsgo was actually found and ran: a report that analyzed nothing
    # would still carry the header above.
    assert_match "1 of 1 source files", output
  end
end
`;

const out = join(repoRoot, "dist-bin", "thicket.rb");
writeFileSync(out, formula);
process.stdout.write(`${out}\n`);
